version: '3.1'

services:
  frontend:
    build:
      context: ./frontend/mainstream-minds
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://127.0.0.1:8080/api
    ports:
      - 80:80

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    environment:
      - DB_CONN=postgresql://postgres:some_password@db:5432/mainstream-minds
      - REDIS_CONN=redis://redis:6379

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: some_password
    ports:
      - 5432:5432
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
